version: "2.4"
services:
  node:
    image: docker.io/tiredpixel/cardano-node-build:head
    volumes:
      - ./bin:/home/x/repo/bin
      - ./bin/.bashrc:/home/x/.bashrc
      - ./lib:/home/x/repo/lib
      - ./mnt/var/lib/cardano:/var/lib/cardano
    networks:
      - node
networks:
  node: {}
